version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: azure_visualizer_backend
    ports:
      - "8000:8000"
    networks:
      - azure_net
    env_file: './backend/.env'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: azure_visualizer_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - azure_net
    env_file: './frontend/.env.local'
networks:
  azure_net:
    driver: bridge
